### ISSUE TITLE
Fatal error - managing Caes and accessing case tab on Contact summary screen

### ISSUE THREAD

**Issue by kcristiano** [twomice/civicrm-caseenddate#2]
Starting in CiviCRM 5.69.5 any attempt to access a case will case a fatal error with this extension enabled. 

From the php error log: 

```
01-Apr-2024 08:45:37 America/New_York] PHP Fatal error:  Uncaught Error: Cannot access protected property CRM_Case_Page_Tab::$_id in /home/example/public_html/wp-content/uploads/civicrm/ext/civicrm-caseenddate/caseenddate.php:13
Stack trace:
#0 /home/example/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(272): caseenddate_civicrm_pageRun()
#1 /home/example/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks()
#2 /home/example/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(310): CRM_Utils_Hook_WordPress->invokeViaUF()
#3 /home/example/public_html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(251): Civi\Core\CiviEventDispatcher::delegateToUF()
#4 /home/example/public_html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#5 /home/example/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(263): Symfony\Com in /home/example/public_html/wp-content/uploads/civicrm/ext/civicrm-caseenddate/caseenddate.php on line 13
```

**Comment by twomice** [comment]
@kcristiano Super easy fix to long-ago rookie coding mistake. Wow, this extension is still in use?

**Comment by kcristiano** [comment]
Thanks @twomice Can we also get a civix update as well for latest php version compatability?

**Comment by twomice** [comment]
Yep, was thinking the same thing. See latest master (also tagged as v1.2.0)

**Comment by kcristiano** [comment]
Thank You!
